### PR TITLE
Add mongodb to docker-compose.yaml

### PR DESCRIPTION
**Pull request by gammazero**
This serves as an updated replacement for PR #7

### CODE REVIEW

**Comment by elijaharita** [comment]
Thanks for doing this.

Is this already running properly for you? I'm trying it out but getting a few errors

```
motion-s3-connector-motion-1                        | 2023-11-10T22:00:54.638Z  ERROR   motion/cmd      motion/main.go:222      Failed to start Singularity blob store  {"err": "failed to set motion identity: Post \"http://http:%2F%2Fsingularity_api:9090/api/identity\": dial tcp: lookup http://singularity_api: no such host (are you using Singularity v0.5.4+?)"}
motion-s3-connector-motion-1                        | 2023-11-10T22:00:54.638Z  ERROR   motion/cmd      motion/main.go:257      failed to set motion identity: Post "http://http:%2F%2Fsingularity_api:9090/api/identity": dial tcp: lookup http://singularity_api: no such host (are you using Singularity v0.5.4+?)
```

**Comment by elijaharita** [comment]
I've been able to get most things running with a few modifications, but for some reason cloudserver is not connecting to mongo despite that i can access it through cli. working on it

**Comment by gammazero** [comment]
@elijaharita 
This finally works with mongdb, but requires a couple extra steps:

Create `keyfile` in `$HOME/.motion/zenko/mongodbMetadata/`
```shell
echo secretkey > $HOME/.motion/zenko/mongodbMetadata/keyfile
chown 999:docker $HOME/.motion/zenko/mongodbMetadata/keyfile
chmod 600 $HOME/.motion/zenko/mongodbMetadata/keyfile
```

Initiate the replica set:
```shell
mongosh -u root -p changeme
rs.initiate({ _id: "rs0", members: [ { _id: 0, host: "mongodb:27017" } ] })
```

**Review by elijaharita — APPROVED** [review]
Just tested it out myself, it works! Amazing!

I did have a bit of issue following the instructions provided since I don't have rootless Docker set up. 

Had to do keyfile setup as root since the motion directory is owned by root (another reason why I think this demo should use a regular named volume instead of mounting to user's home dir - root-owned files in user dir?)

```
sudo su
echo secretkey > /home/[my user]/.motion/zenko/mongodbMetadata/keyfile
chmod 600 /home/[my user]/.motion/zenko/mongodbMetadata/keyfile
```

**Pull request merged**
